Add Traditional Chinese (zh_tw.json)
yungnickyoung/YUNGs-Menu-Tweaks pull request #9
Opened 2024-08-08 16:58 UTC by yichifauzi

Add Traditional Chinese localization

2024-10-01 14:58 UTC, notlin4 requested changes

2024-10-01 14:58 UTC, notlin4 commented on Common/src/main/resources/assets/bettermenu/lang/zh_tw.json
> +  "text.autoconfig.yungsmenutweaks-fabric-1_20_1.option.yungsMenuTweaks.backgroundTexture.@Tooltip[0]": "一個 16x16 的紋理，用作自訂背景，而不是典型的泥土。",
```suggestion
  "text.autoconfig.yungsmenutweaks-fabric-1_20_1.option.yungsMenuTweaks.backgroundTexture.@Tooltip[0]": "一個 16×16 的紋理，用作自訂背景，而不是典型的泥土。",
```

2024-10-01 14:58 UTC, notlin4 commented on Common/src/main/resources/assets/bettermenu/lang/zh_tw.json
> +  "text.autoconfig.yungsmenutweaks-fabric-1_20_1.title": "YUNG's 選單調整",
```suggestion
  "text.autoconfig.yungsmenutweaks-fabric-1_20_1.title": "YUNG 的選單調整",
```

2025-02-04 19:25 UTC, merged

2025-02-04 19:25 UTC, yungnickyoung commented
Thanks!!